### ISSUE TITLE
How to get rid of the dashed line

### ISSUE THREAD

**Issue by rzel** [CreativeBulma/bulma-tooltip#18]
How do I get rid of the dashed line? I noticed buttons don't have it, but I have an anchor tag that is styled as a bulma button, and it has the dashed line. There doesn't seem to be a way.

**Comment by dangowans** [comment]
Try this.

```css
[data-tooltip] {
border-bottom-width: 0 !important;
}
```
